version: "3.2"

networks:
  front-tier:
  back-tier:

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.8.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - metrics:metrics
    networks:
      - back-tier

  grafana:
    container_name: grafana
    image: grafana/grafana:6.0.2
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana:Z
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
 
  metrics:
    container_name: metrics
    tty: true
    stdin_open: true
    expose:
      - 9171
    ports:
      - 9171:9171
    build:
      context: github-exporter
    image: infinityworks/github-exporter:latest 
    environment:
      - REPOS=elastos/Elastos.ELA, elastos/Elastos.NET.Carrier.Native.SDK, elastos/Elastos.ELA.SideChain, elastos/Elastos.ELA.SPV, elastos/Elastos.Trinity, cyber-republic/CyberRepublic
      - BRANCH=master
      - LOG_LEVEL=info
      - GITHUB_TOKEN=<Your github token>
    networks:
      - back-tier
