{
 "title": "GitHub Statistics",
 "description": "A docker stack which uses Grafana to collect GitHub statistics for selected Repositories",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Latest Commits",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(github_commit_latest) by (author, branch, commithash, date, repo)",
     "legendFormat": "{{date}} | {{repo}} | {{branch}} | {{author}} | {{commithash}}"
    }
   ]
  },
  {
   "title": "Commits: elastos/Elastos.ELA",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(github_commit_count{repo=~\"elastos/Elastos.ELA$\"})"
    }
   ]
  },
  {
   "title": "Commits: elastos/Elastos.NET.Carrier.Native.SDK",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(github_commit_count{repo=~\"elastos/Elastos.NET.Carrier.Native.SDK$\"})"
    }
   ]
  },
  {
   "title": "Commits: elastos/Elastos.ELA.SideChain",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(github_commit_count{repo=~\"elastos/Elastos.ELA.SideChain$\"})"
    }
   ]
  },
  {
   "title": "Commits: elastos/Elastos.ELA.SPV",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(github_commit_count{repo=~\"elastos/Elastos.ELA.SPV$\"})"
    }
   ]
  },
  {
   "title": "Commits: elastos/Elastos.Trinity",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(github_commit_count{repo=~\"elastos/Elastos.Trinity$\"})"
    }
   ]
  },
  {
   "title": "Commits: cyber-republic/CyberRepublic",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(github_commit_count{repo=~\"cyber-republic/CyberRepublic$\"})"
    }
   ]
  },
  {
   "title": "Number of Stars",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "github_repo_stars", "legendFormat": "{{repo}}" }
   ]
  },
  {
   "title": "Number of Open Issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "github_repo_open_issues", "legendFormat": "{{repo}}" }
   ]
  },
  {
   "title": "Number of Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "github_repo_forks", "legendFormat": "{{repo}}" }
   ]
  }
 ]
}